// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"github.com/FelipeMP0/go-orchestration-choreography-comparison/service/v2/datastore"
	"github.com/FelipeMP0/go-orchestration-choreography-comparison/service/v2/listener"
)

// Injectors from wire.go:

func Initialize() *App {
	client := datastore.NewMongoClient()
	database := datastore.NewDatabase(client)
	serviceStateDatastore := datastore.NewServiceStateDatastore(database)
	amqpListener := listener.NewAMQPListener()
	app := NewApp(client, serviceStateDatastore, amqpListener)
	return app
}
