version: "3.7"
services:
  microservice1:
    container_name: microservice1
    build: .
    environment: 
      MONGO_CONNECTION_STRING: "mongodb://root:password@mongodb:27017"
      FORCE_FAIL: "false"
    depends_on: 
      - mongodb
    volumes:
      - ./microservices_configuration/config_index1.json:/microservices_configuration/config.json
    depends_on: 
      - activemq-artemis
      - mongodb1

  microservice2:
    container_name: microservice2
    build: .
    environment: 
      MONGO_CONNECTION_STRING: "mongodb://root:password@mongodb:27017"
      FORCE_FAIL: "false"
    depends_on: 
      - mongodb
    volumes:
      - ./microservices_configuration/config_index2.json:/microservices_configuration/config.json
    depends_on: 
      - activemq-artemis
      - mongodb1

  microservice3:
    container_name: microservice3
    build: .
    environment: 
      MONGO_CONNECTION_STRING: "mongodb://root:password@mongodb:27017"
      FORCE_FAIL: "false"
    depends_on: 
      - mongodb
    volumes:
      - ./microservices_configuration/config_index3.json:/microservices_configuration/config.json
    depends_on: 
      - activemq-artemis
      - mongodb1

  # microservice4:
  #   container_name: microservice4
  #   build: .
  #   environment: 
  #     MONGO_CONNECTION_STRING: "mongodb://root:password@mongodb:27017"
  #     FORCE_FAIL: "false"
  #   depends_on: 
  #     - mongodb
  #   volumes:
  #     - ./microservices_configuration/config_index4.json:/microservices_configuration/config.json
  #   depends_on: 
  #     - activemq-artemis
  #     - mongodb1
  
  # microservice5:
  #   container_name: microservice5
  #   build: .
  #   environment: 
  #     MONGO_CONNECTION_STRING: "mongodb://root:password@mongodb:27017"
  #     FORCE_FAIL: "false"
  #   depends_on: 
  #     - mongodb
  #   volumes:
  #     - ./microservices_configuration/config_index5.json:/microservices_configuration/config.json
  #   depends_on: 
  #     - activemq-artemis
  #     - mongodb1

  # microservice6:
  #   container_name: microservice6
  #   build: .
  #   environment: 
  #     MONGO_CONNECTION_STRING: "mongodb://root:password@mongodb:27017"
  #     FORCE_FAIL: "false"
  #   depends_on: 
  #     - mongodb
  #   volumes:
  #     - ./microservices_configuration/config_index6.json:/microservices_configuration/config.json
  #   depends_on: 
  #     - activemq-artemis
  #     - mongodb1
  
  # microservice7:
  #   container_name: microservice7
  #   build: .
  #   environment: 
  #     MONGO_CONNECTION_STRING: "mongodb://root:password@mongodb:27017"
  #     FORCE_FAIL: "false"
  #   depends_on: 
  #     - mongodb
  #   volumes:
  #     - ./microservices_configuration/config_index7.json:/microservices_configuration/config.json
  #   depends_on: 
  #     - activemq-artemis
  #     - mongodb1

  # microservice8:
  #   container_name: microservice8
  #   build: .
  #   environment: 
  #     MONGO_CONNECTION_STRING: "mongodb://root:password@mongodb:27017"
  #     FORCE_FAIL: "true"
  #   depends_on: 
  #     - mongodb
  #   volumes:
  #     - ./microservices_configuration/config_index8.json:/microservices_configuration/config.json
  #   depends_on: 
  #     - activemq-artemis
  #     - mongodb1

  mongodb1:
    container_name: mongodb
    image: mongo:4.4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - "27017:27017"

  activemq-artemis:
    container_name: activemq-artemis
    image: vromero/activemq-artemis:2.15.0-alpine
    environment:
      ARTEMIS_USERNAME: user-amq
      ARTEMIS_PASSWORD: password-amq
    ports:
      - 8161:8161
      - 61616:61616

networks: 
  default:
    name: "default_network"
